#
# Module manifest for module 'Influx'
#
# Generated by: Mark Wragg
#
# Generated on: 02/01/2018
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Influx.psm1'

# Version number of this module.
ModuleVersion = '1.0.0.1'

# ID used to uniquely identify this module
GUID = 'a66d3512-0010-4c64-bc50-2b87433f8de9'

# Author of this module
Author = 'Mark Wragg'

# Company or vendor of this module
CompanyName = 'Wragg.io'

# Copyright statement for this module
Copyright = '(c) 2017 Mark Wragg. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A PowerShell module for interacting with the time-series database platform Influx: https://www.influxdata.com/'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @('Send-Statsd', 'Write-Influx', 'Write-InfluxUDP', 
               'Send-3ParSystemMetric', 'Send-3ParVirtualVolumeMetric', 
               'Send-IsilonStoragePoolMetric', 'Send-TFSBuildMetric', 
               'Send-DatacenterMetric', 'Send-DatastoreClusterMetric', 
               'Send-DatastoreMetric', 'Send-HostMetric', 'Send-ResourcePoolMetric', 
               'Send-VMMetric')

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Influx','InfluxDB'

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/markwragg/Powershell-Influx'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'https://github.com/markwragg/Powershell-Influx/blob/master/README.md'

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

